### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by Cptmorgsttv** [Scarso327/AltisLife-Framework#431]
Sorry for the trouble having issues with initial setup when ever I've selected player slot and loading in I'm stuck on a black screen I can respawn then load for the first time but any actions I make arent saved and also unable to access any sort of inventory etc, willing to provide compensation if anybody could help me with this as I've seen the epic work been put into this and would like to get the server up and running ASAP

**Comment by YarneS21** [comment]
How did you fix it?

**Comment by Scarso327** [comment]
@YarneS21 https://github.com/Scarso327/AltisLife-Framework/issues/432#issuecomment-2083800622

Checkout this comment, I'd be pretty confident this is the issue.
