### ISSUE TITLE
Future Updates

### ISSUE THREAD

**Issue by Cptmorgsttv** [Scarso327/AltisLife-Framework#433]
Sorry if this is the wrong place to ask I was wondering if you were still planning on updating the framework or has your focus shifted to other projects as the progress so far has been amazing, also side note would it be possible to explain how to use the admin functions etc

**Comment by Scarso327** [comment]
Hi, focus has shifted from this project as there wasn't any interest as arma 3 has slowed died.

Feel free to contribute using pull requests here and I'll review them if you're looking to add new features and changes. Or make an issue with a suggestion for a feature for someone to pick up and add themselves.

**Comment by Scarso327** [comment]
`Functions/Inputs/fn_KeyUp.sqf`

This file contains the key bind to access the admin commands. We use preprocessors so the keys are shown in code for easy reading, anything with `ULP_fnc_isStaff ` in the condition is an admin command. You should be able to figure it out from there.

**Quick Overview**

- Shift + F1 toggles Admin
- Shift + F2 is the admin camera (This is our admin menu as it is where most user interaction takes place)
- Shift + F3 toggles invis

The admin camera's map allows you to teleport etc.
