### ISSUE TITLE
Question about crafting

### ISSUE THREAD

**Issue by sleeplyzzz** [Scarso327/AltisLife-Framework#434]
hi!

I just tried the framework and I am in love with it. Now to my question, is it possible to craft Weapons, Ammunition and other Equipment with the crafting system? Or was it never meant to do it?

**Comment by Scarso327** [comment]
The system is currently only designed around virtual items. It was meant to be how you'd acquire gear for major crimes and craft less valuable archeology items into ones with significantly more value.

Physical items were talked about but left out of the original project scope.

**Comment by sleeplyzzz** [comment]
Thank you so much for letting me know! Still I think this framework is amazing and I will work on it for my new project. Slowly getting the hang of it. Thank you so much for making this public and for the fast answer.
