### ISSUE TITLE
also black screen when loading 

### ISSUE THREAD

**Issue by MikeyInfiniteDev** [Scarso327/AltisLife-Framework#437]
These are the only faults i see inside the monitor not sure if you can help with the little info we tried almost everything i think we know 
(database version 9.0.1)

Scripting function 'bis_fnc_execvm' is not allowed to be remotely executed
User mikes [KCT] (***redacted***) tried to remoteExec a disabled function
Ragdoll - loading of ragdoll source "Soldier" started.
Ragdoll - loading of ragdoll source "Soldier" finished successfully.
Client: Remote object 4:0 not found
EPE manager release (0|4|0)
Deinitialized shape [Class: "C_Soldier_VR_F"; Shape: "a3\characters_f_bootcamp\common\vr_soldier_f.p3d";]
Deinitialized shape [Class: "Underwear_F"; Shape: "a3\characters_f\common\basicbody.p3d";]
Deinitialized shape [Class: "C_man_1"; Shape: "a3\characters_f\civil\c_poloshirt.p3d";]
Deinitialized shape [Class: "C_man_polo_3_F"; Shape: "a3\characters_f\civil\c_poloshirt.p3d";]
Deinitialized shape [Class: "C_man_polo_1_F"; Shape: "a3\characters_f\civil\c_poloshirt.p3d";]
Deinitialized shape [Class: "B_G_Soldier_M_F"; Shape: "a3\characters_f_gamma\guerrilla\ig_guerrilla3_1.p3d";]
d:\bis\source\stable\futura\lib\network\networkserver.cpp ClearNetServer:NOT IMPLEMENTED - briefing!
Extensions:
  extDB3 (C:\Users\Administrator\Desktop\steamcmd\steamapps\common\Arma 3 Server\@extDB3\extDB3_x64.dll) [extDB3 v1033 Windows]

**Comment by Scarso327** [comment]
Hey Mikey, it'll not be easy to help without full RPT logs. Could you post them please?

**Comment by MikeyInfiniteDev** [comment]
https://pastebin.com/KEth1pa1 

should be the full RPT log 
i do see that it says game DIR empty now xD so do i have to make a pbo out of it ?

**Comment by Scarso327** [comment]
`Arma 3 Server\@life_server\addons\life_server.pbo` would be the expected path normally

**Comment by MikeyInfiniteDev** [comment]
yeah just as i posted the issue we both went like " Ohhhhhh " Lmao 
il let you know in a sec gonna make a pbo out of it xD

**Comment by MikeyInfiniteDev** [comment]
New fault now , still black screen tho 

https://pastebin.com/Lybfi4JH

**Comment by Scarso327** [comment]
`2024/08/10, 23:25:43 "extDB3: Error with Database Connection"`

Check the @extdb file it'll have a logs file in there with further errors

**Comment by MikeyInfiniteDev** [comment]
extDB3: https://bitbucket.org/torndeco/extdb3/wiki/Home
extDB3: Version: 1.031
extDB3: Windows Version
Message: All development for extDB3 is done on a Linux Dedicated Server
Message: If you would like to Donate to extDB3 Development
Message: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2SUEFTGABTAM2
Message: Also leave a message if there is any particular feature you would like to see added.
Message: Thanks for all the people that have donated.
Message: Torndeco: 18/05/15


extDB3: Found extdb3-conf.ini
extDB3: Detected 4 Cores, Setting up 4 Worker Threads
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...


[23:42:34:127701 +02:00] [Thread 7988] extDB3: Config Error: altislife: No such node (altislife.IP)

seems like everything is setup right tho 



[Main]
Version = 1

Randomize Config File = false
;; Randomizes Config File after loading.
;;   Recommend to turn on, if you have enabled filepatching on arma.

Allow Reset = false
;; Allows 9:RESET, usefull for development work

Thread = 0
;; Option to force number of worker threads for extDB3.
;;   Auto = 0, Min = 2, Max = 6

[Log]
Flush = true
;; Flush logfile after each update.
;;    Option really only usefull if running DEBUG BUILD


[lucky_arma3]
IP = ***.*.***.*
Port = 3306
Username = lucky_arma3
Password =  (****Redacted****)
Database = lucky_arma3

**Comment by Scarso327** [comment]
change `lucky_arma3` to `altislife`

**Comment by MikeyInfiniteDev** [comment]
soo database wasnt working right so we started a local one on the dedicated server and when trying to import the sql we get this now 

https://pastebin.com/9E9Kr5ng

**Comment by Scarso327** [comment]
What database are you using?

**Comment by Lucky13-Infiniti** [comment]
Hey @Scarso327 i fall in for @MikeyInfiniteDev 
We are using xampp for the mysql

**Comment by Lucky13-Infiniti** [comment]
Okay fond the problem :) he used unicode

**Comment by Lucky13-Infiniti** [comment]
Still got a black screen:
https://pastebin.com/ZQyZaBKU

**Comment by MikeyInfiniteDev** [comment]
after a bit of tinkering we got everything to start without errors 
now we have the problem that you cannot choose a spawnpoint (not as CIV , COP , or Medic) 
we looked around but really dont seem to find whats up with it 
my friend will upload the logs but idk if that will help 
i added you on discord idk when you have time to help 

thx <3

**Comment by Lucky13-Infiniti** [comment]
https://pastebin.com/2sYW82bd

**Comment by Lucky13-Infiniti** [comment]
Okay i found the problem :)
I tested the map Altis and that one is working fine now
But we were doing Tanoa and there are no spawn scripts for Tanoa
Is there a way we can get those?

**Comment by Scarso327** [comment]
https://github.com/Scarso327/AltisLife-Framework/blob/development/Client%20Side/Framework/Functions/Spawn/CfgSpawns.hpp

You can configure spawns in the file above. 

Hot keys can be found in the 3 files below

https://github.com/Scarso327/AltisLife-Framework/blob/development/Client%20Side/Framework/Functions/Input/fn_keyDown.sqf

https://github.com/Scarso327/AltisLife-Framework/blob/development/Client%20Side/Framework/Functions/Input/fn_KeyUp.sqf

https://github.com/Scarso327/AltisLife-Framework/blob/development/Client%20Side/Framework/Functions/Admin/fn_adminCamera.sqf

It's easy to know what key is being used where as we use preprocessor and https://github.com/Scarso327/AltisLife-Framework/blob/development/Client%20Side/Framework/dikCodes.hpp to show the actual key being pressed instead of the number that represents it.

**Comment by MikeyInfiniteDev** [comment]
thanks
