### ISSUE TITLE
The server is not working fully

### ISSUE THREAD

**Issue by NemerSM** [Scarso327/AltisLife-Framework#438]
Hello brother, I have a problem when entering the server. The server settings do not work completely. When entering the server, it is as same entering the Editor mode. For example, when entering as a policeman, I cannot control the doors of the police station, the prison door, or the airport door. Is there a solution to this problem? Thank you.

**Comment by NemerSM** [comment]
i am use custom map 
saint-martin

**Comment by Scarso327** [comment]
Hello,

This is very unlikely to be an issue with the mission; instead, it'll be something that was missed when adding the new map.

`CfgMaps`, `CfgSpawns`, `CfgPrison`, `CfgCameras`, `CfgCrimes` all have a world dependency in their namespaces.

`Cfg > WorldName` is the structure you'll see being used for Altis.

Another thing you'll need to make sure you do is set the faction of the "slots". The code below should be against the unit's init section. The "Civilian" tag here should match a class specified in `CfgFactions`.
`[this, "Civilian", true] call ULP_fnc_setFaction;`

**Comment by NemerSM** [comment]
ok  i will be checked that thankyou

**Comment by NemerSM** [comment]
i will be change all cfg to my new map and positon but still same i can not contorl the gate and police building

**Comment by NemerSM** [comment]
main gate
https://prnt.sc/ZIAD-2fvhJ60

police buliding
https://prnt.sc/Ej7MmFHUzFN5

**Comment by NemerSM** [comment]
this is my orginal server its working 
https://prnt.sc/M08VAafkny2x
https://prnt.sc/lY0QuHiVBUOm
https://prnt.sc/8s0-VguBLpRD

**Comment by Scarso327** [comment]
Hi Nemer,

This isn't a problem related to this mission. You'll find they added the scroll actions on user load or something that isn't featured in this mission. I'd recommend contacting the map's original developers if you're unsure how they add the scroll action and implement it into this mission for your use case.

**Comment by NemerSM** [comment]
ok thankyou bro for helping

**Comment by NemerSM** [comment]
i will be talk to orginal developers of map he said the role is 
player getVariable ['copLevel',0]

**Comment by NemerSM** [comment]
https://epochmod.com/forum/topic/36781-where-i-have-to-put-the-code-for-entering-the-policestation/?do=findComment&comment=256035

**Comment by NemerSM** [comment]
its work now after add
 player setVariable["copLevel", 1, true];
 on fn_initPolice
