### ISSUE TITLE
Black Screen After Install

### ISSUE THREAD

**Issue by ToastyZA** [Scarso327/AltisLife-Framework#439]
Hi,

I have downloaded the development branch and setup the server as explained and to my understanding, however im getting a black screen after selecting my player slot and loading the mission file.

I have only run the SQL and not the migration one.

Not sure if i have missed a step.

[Server & EXTDB3 RPTs.zip](https://github.com/user-attachments/files/17821315/Server.EXTDB3.RPTs.zip)

**Comment by Scarso327** [comment]
Hi @ToastyZA 

You're getting this error in your sql logs

`[22:47:00:427021 +02:00] [Thread 5624] extDB3: SQL: Error MariaDBQueryException: Duplicate entry '1' for key 'PRIMARY'
[22:47:00:427042 +02:00] [Thread 5624] extDB3: SQL: Error MariaDBQueryException: Input: INSERT INTO community_goals (id, goal_cfg, end_date) VALUES ('1', 'SellCigarette', DATE_FORMAT(ADDDATE(CURDATE(), INTERVAL 14 DAY), '%Y-%c-%e'));`

I'd recommend clearing the "community_goals" table and restarting the server.

**Comment by ToastyZA** [comment]
Thanks for the quick reply @Scarso327 

I saw this in on of the other comments and tried this and the same issue is still happening.

I can hear myself walking around in water and that but the black screen stays.

**Comment by ToastyZA** [comment]
Didn't work either, attached latest logs.

[Server & EXTDB3 RPTs - 2.zip](https://github.com/user-attachments/files/17821752/Server.EXTDB3.RPTs.-.2.zip)

**Comment by Scarso327** [comment]
Could you use https://pastebin.com/ please? For security I have to do virus scans on files so it's just easier to use the site.

That error is fine.

**Comment by Scarso327** [comment]
Without wiping the current goals table state can you run `SHOW TABLE STATUS LIKE 'community_goals'`

I think it's the fn_getNextId script getting the same id each time which I wouldn't expect but assuming you've wiped the table the auto increment _should_ work

**Comment by ToastyZA** [comment]
This is what the table is showing.

https://pastebin.com/GmB6EvQk

**Comment by Scarso327** [comment]
Okay - Could you try restarting the server and seeing if the SQL error changes? The `Auto_increment` value is used from that query to get the "next id" for a table so 2 _should_ be fine

**Comment by ToastyZA** [comment]
Looks to be the same.

https://pastebin.com/TDL81i6h

**Comment by Scarso327** [comment]
To try and see if we can get in "fn_initCommunityGoals"

lines 44 - 66, try commenting this out and repacking the life server file. I'll try and have a closer look tomorrow.

**Comment by ToastyZA** [comment]
Thanks. I’ll try this first thing tomorrow when I’m back from work and give you an update.  Appreciate the assistance.

**Comment by ToastyZA** [comment]
Morning, managed to make the changes from work and booted the server, below is the new log file.

https://pastebin.com/p5SJet8Y

I haven't tested connecting as a player as of yet due to being at work. But will have someone in about 3hrs who will be able to connect for me and give me feedback

**Comment by ToastyZA** [comment]
> To try and see if we can get in "fn_initCommunityGoals"
> 
> lines 44 - 66, try commenting this out and repacking the life server file. I'll try and have a closer look tomorrow.

Did this now and connected to the server.

Database doesn't enter anything into the _community_goals_ table now, but still on a black screen.

**Comment by ToastyZA** [comment]
Sooooo i changed to 32bit Server exe and it worked xD

**Comment by Scarso327** [comment]
Apologies for the delay, I am glad you got it sorted but the bit version shouldn't have an effect on the mission.

Are you sure you didn't perform another troubleshooting step at the same time that could have resolved it?

**Comment by ToastyZA** [comment]
No worries man.

Not that I can recall. I am using AMP Manager to control the server. I will do a test a bit later of switching back to 32bit and see what happens and let you know

**Comment by ToastyZA** [comment]
Ok so server was running now on x32.exe

Shut it down and switched to x64.exe and started back up, connected to server and black screen.

Put the server back up on x32.exe and connected just fine.

No other adjustments were made between the switching

**Comment by Scarso327** [comment]
Thanks for giving that a quick test - as you've got it working, I won't prioritise getting around to it, but I'll have a play to see if I can find an issue with 64-bit servers. I haven't got a local environment setup at the moment as it's been a while since I've done arma development.

**Comment by ToastyZA** [comment]
No worries thanks man! Once again thanks for the amazing framework and sharing it with us.

**Comment by ToastyZA** [comment]
The Dev i have helping me now is also testing on his local environment using TADST to do the setup and is running into the same issue on the 64bit exe. He has a feeling it may be extdb3 as there are a few errors, But he is gonna do a proper dive into it all later today to see if he can resolve the issue.

**Comment by FabricinBR** [comment]
I'm having the same problem opening the server and connecting. 

I tried changing the version to 32 bits but it didn't work.

**Comment by FabricinBR** [comment]
I just respawned when entering the server when the black screen occurs and everything is resolved. 

It's something related to the spawn when entering the server for the first time.

**Comment by Scarso327** [comment]
This issue should now be resolved with PR #444 

@FabricinBR—Looking through your logs, none of the server-side init logs are showing, meaning you've likely not configured life_server correctly. Make sure you have a folder "@life_server" with "addons" inside, and then inside that, the life_server file from the repo packed using PBO Manager. If that fails to fix your issue, please open another one, as yours is unrelated to this one. Thank you.
