### ISSUE TITLE
Altis mission.sqm [request]

### ISSUE THREAD

**Issue by KiilluaZA** [Scarso327/AltisLife-Framework#440]
Hi there, we are using your framework, and everything is working great so far thank you very much for the files and framework. 

We are using the Altis mission file and would like to make some changes to the map. However, the Altis mission.sqm is binarized and we can't make changes. is this meant to be if not could we please get open mission.sqm.

thanks in advance

**Comment by Scarso327** [comment]
The binarisation of the shouldn't stop it from being opened within the arma 3 editor. If you have a tool that needs it removed you can do it yourself from the editor when viewing the missions settings. It's a checkbox.
