### ISSUE TITLE
Some help with the altis life

### ISSUE THREAD

**Issue by Rebecca3535** [Scarso327/AltisLife-Framework#441]
Hello! first off thank you very much for this framework i love it. I have over the past week been working on it to make just how i want my server to be.  As you are the best person to ask about these things i am here. First off a question. Can money be duped. I have tested and tried but not success and thats great.. How ever after testing i have come across a dupe issue where if any items are placed in a car/Vehicle virtual or guns etc and the player instantly logs off and comes back those items are in the car and in there inventory. and this can be duping high value things. Yes good admin work watching these things can catch some but i would rather try patching it.

Issue 2. When a player is shot and downed, If they also instantly log off and log back in they are back up and have all gear. I know if they stay down for a bit and do this then it will fresh spawn them. But the alt f4 right after seems to work. Yes i will ban for combat log but i cant be everywhere so greatly a patch possible would be great.  

I tested player going to jail and they could just respawn and get out. I disabled respawning option for now to combat this. Also when a player is released from prison they spawn outside but then the player is stuck and keeps spawning back in that same place over and over. Even when i TP them to me they tp back to the release GPS. maybe something in the prison release script i cannot see how to fix this. You might and wouldbe amazing.

lastly might you have all the altis life key binds? I cant find them anywhere.

Again thank you for the brill framework. My dreams of making a UK altis life is slowly coming true. I know its hard now that its old but still saved my easy over a year of work.. Cheers. 

Rebecca.

**Comment by Scarso327** [comment]
@Rebecca3535 Hello!

I've raised a draft PR #442 that should fix the disconnect on incap issue by wiping their gear. If you could report back how this goes I'd appreciate it!

I'll get back to you on the other issues shortly.

**Comment by Rebecca3535** [comment]
> @Rebecca3535 Hello!
> 
> I've raised a draft PR #442 that should fix the disconnect on incap issue by wiping their gear. If you could report back how this goes I'd appreciate it!
> 
> I'll get back to you on the other issues shortly.

Thanks do i just paste in the green highlighted section of code?

**Comment by Scarso327** [comment]
Yeah you can just copy the changes I've made or pull down and copy the files over from the `feat/wipe-gear-on-dead-disconnect` branch

**Comment by Rebecca3535** [comment]
Thanks for that! I will upload that change later and let you know how the testing goes. As for the duping items with a vehicle. may i surgest that when the player logs off the car they own gets put back in the garage that way items desoawn in the car as i have tested. Yes they could use someone elses car but its some sort of fix. 

Also the work bench does not work based off our testing. 

Another odd bug is the notifications on the left for pay check etc sometimes they dont go away and leaves a long list of messages. Its find for now logging helps but just letting you know (:

**Comment by Scarso327** [comment]
@Rebecca3535 #445 fixes the disconnect issue

**Comment by Scarso327** [comment]
Also, the workbench doesn't have an action or anything. Certain blueprints require you to be close to it when you craft things. 

When you're in the inventory's crafting screen, you'll be able to make them—the same way Rust works if you've ever played that.

**Comment by Rebecca3535** [comment]
awesome i will test this tonight. and as for the work bench i will also test this. As i am trying to run this RP server this all helps alot and i will be getting a few bug messages here and there. One more thing please Scarso. With the built in admin menu it all works fine i just cant use it as shift f2 brings up the congfig menu. and htis is the same keybind as the admin menu (As i fun infistar too) is there a way to rebind this. THANKS Again

**Comment by Scarso327** [comment]
Rebinding these would be a process you'd need to go through as it's not something that's configurable out of the box.

`Functions > Inputs > fn_KeyUp.sqf`

If you search for "case F2:" you'll see the code that handles the opening of the admin menu. You can change conditions here. You'll see the variables "_shift", "_ctrlKey", and "_alt" are available in here to check for those key presses as well.

We use the preprocessor to make the cases more human-readable to you can see what keys are currently defined in `dikCodes.hpp`. If you want to use a key that isn't here then you'll need to define it. You can find all dik codes at https://community.bistudio.com/wiki/DIK_KeyCodes

**Comment by Rebecca3535** [comment]
> Rebinding these would be a process you'd need to go through as it's not something that's configurable out of the box.
> 
> `Functions > Inputs > fn_KeyUp.sqf`
> 
> If you search for "case F2:" you'll see the code that handles the opening of the admin menu. You can change conditions here. You'll see the variables "_shift", "_ctrlKey", and "_alt" are available in here to check for those key presses as well.
> 
> We use the preprocessor to make the cases more human-readable to you can see what keys are currently defined in `dikCodes.hpp`. If you want to use a key that isn't here then you'll need to define it. You can find all dik codes at https://community.bistudio.com/wiki/DIK_KeyCodes

thanks. Thats a little too much for me i wouldnt wanna break anything.  Can you add me on DC?  iisabellaa

**Comment by Scarso327** [comment]
@Rebecca3535 

I've done an experimental fix for the item duping through vehicles that can be accessed via #451. 

From my testing, it works well to ensure the player's gear is synced whenever they disconnect and isn't just applicable to the vehicle dupe issue. I will delay adding this to the main framework until I've had more time to validate it properly. You can do as you did before and implement it by copying the green parts.

I avoid adding on Discord if I can help it for these issues, do you have someone working on your project that could have a go at making the changes? I am happy to communicate through this issue for now.

**Comment by Scarso327** [comment]
Fix for the hints not being removed can be found #452 

Fix for prison issues can be found in #453 but it **requires** #452 to be implemented first.

**Comment by Rebecca3535** [comment]
> @Rebecca3535
> 
> I've done an experimental fix for the item duping through vehicles that can be accessed via #451.
> 
> From my testing, it works well to ensure the player's gear is synced whenever they disconnect and isn't just applicable to the vehicle dupe issue. I will delay adding this to the main framework until I've had more time to validate it properly. You can do as you did before and implement it by copying the green parts.
> 
> I avoid adding on Discord if I can help it for these issues, do you have someone working on your project that could have a go at making the changes? I am happy to communicate through this issue for now.

Thanks Scarso for the time into putting these fixes in! I use this framework for a live UK server only been up a week now. Its great. No i dont have any Devs as i have only just made this comunity. I tried getting some from fiver but got scammed once and the rest over charage me. So who better to ask than the person who wrote most of it. All i have been doing is map things and just moving some numbers around to try balance the prices a bit. broke the server a few times but went to a back up. I would be willing to pay you for your work toward making this framework more playable (Pretty much everything works tho). Not to add anything just iron out the bugs. Thats why I asked to add you on DC. If not thats fine. Just a bug list is slowly pileing up. 

Thanks again for the work i will be adding these changes soon. as for the disconnect when down fix that 100% works combat logging when down can no longer happen (:

**Comment by Scarso327** [comment]
@Rebecca3535 

I am not looking for paid work but I am more than happy to resolve issues if required. All I ask is you create a new bug report for each via https://github.com/Scarso327/AltisLife-Framework/issues/new/choose. This way everyone that uses the framework benefits from the work and it has no cost for you.

To help with managing issues I am going to close this one now, if you find any of the fixes hasn't resolved the issue correctly please create another separate issue using the link above. It makes it easier to manage.
