### ISSUE TITLE
Database setup problem 

### ISSUE THREAD

**Issue by Bucket21-Gif** [Scarso327/AltisLife-Framework#474]
Every time i am trying to setup the sql database i get and error 

/* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IF NOT EXISTS `deleteOldElection`()
BEGIN
	DELETE FROM votes WHERE `active`='0'' at line 4 */

Have tried speaking to my hosting provider and they cannot find the problem they have made sure everything is correct for what you have stated.
Thanks.

**Comment by Scarso327** [comment]
Hey @Bucket21-Gif 

Which sql file are you using altislife.sql or altislife_mysql_8_0_13.sql?

**Comment by Bucket21-Gif** [comment]
altislife.sql or altislife_mysql_8_0_13.sql

**Comment by Bucket21-Gif** [comment]
altislife_mysql_8_0_13.sql

**Comment by Scarso327** [comment]
Have you tried the alitslife.sql file? It should work depending on your database.

**Comment by Bucket21-Gif** [comment]
Same error

**Comment by Scarso327** [comment]
@Bucket21-Gif remove all instances of "IF NOT EXISTS" after "CREATE PROCEDURE" and see how that goes

**Comment by Bucket21-Gif** [comment]
/* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 6 */

**Comment by Scarso327** [comment]
Could you provide me with your file?

**Comment by Bucket21-Gif** [comment]
No problem do u want me to send file or pastebin ?

**Comment by Scarso327** [comment]
pastebin is easiest

**Comment by Bucket21-Gif** [comment]
https://pastebin.com/gztqeeVK

**Comment by Bucket21-Gif** [comment]
innodb_version 5.5.48-MariaDB-37.8
protocol_version 10
slave_type_conversions
version 5.5.49-MariaDB
version_comment mariadb.org binary distribution
version_compile_machine AMD64
version_compile_os Win64

**Comment by Scarso327** [comment]
@Bucket21-Gif 

https://pastebin.com/LWxbWUqp

give this file a go please

**Comment by Bucket21-Gif** [comment]
Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(now()),
  `insert_time` timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY (`i' at line 20 */
/*  */

**Comment by Scarso327** [comment]
https://pastebin.com/nTXANGv8

Updated the collations

**Comment by Bucket21-Gif** [comment]
/* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(now()),
  `insert_time` timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY (`i' at line 20 */

**Comment by Scarso327** [comment]
You need to get your provider to update your database to at least MariaDB 10.0.1. 

I'd recommend 10.2.1.

**Comment by Bucket21-Gif** [comment]
Okay will give that a try and update thank you

**Comment by Bucket21-Gif** [comment]
/*!50003 SET sql_mode              = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION' */ ;
/*  */
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`localhost`*/ /*!50003 TRIGGER `logs_after_insert` AFTER INSERT ON `logs` FOR EACH ROW BEGIN
	INSERT INTO logs_queue (log_id) VALUES (NEW.id);
END */;


**/* SQL Error (1227): Access denied; you need (at least one of) the SUPER privilege(s) for this operation */**

**Comment by Scarso327** [comment]
You'll need to replace the "root" name here with the username of the account you're using to login

**Comment by Bucket21-Gif** [comment]
still coming up with the same problem

**Comment by Rebecca3535** [comment]
Having same issues here 

"<infiSTAR.de>CONNECTLOG| 0h 2min | Connected: Yeshin(7623419813374444 - 4) - time: 89.909 - serverFPS: 47.7612 [19-12-2024 11-14-06 - v0260]"
Scripting function 'bis_fnc_arsenal' is not allowed to be remotely executed
User Yeshin (7623419813374444 ) tried to remoteExec a disabled function: 'bis_fnc_arsenal'

**Comment by Bucket21-Gif** [comment]
Have got it working now asked the provider to upload that file for me. Thank you for your help

**Comment by Bucket21-Gif** [comment]
ive now got a black screen when i load in and can hear myself walking about if i press re spawn it allows me to pick a location and actually spawns in but the y menu wont show if i buy a car it dosent spawn any idea why this is ?
