### ISSUE TITLE
 black screen

### ISSUE THREAD

**Issue by Bucket21-Gif** [Scarso327/AltisLife-Framework#475]
i got a black screen when i load in and can hear myself walking about if i press re spawn it allows me to pick a location and actually spawns in but the y menu wont show if i buy a car it dosent spawn any idea why this is ?

_Originally posted by @Bucket21-Gif in https://github.com/Scarso327/AltisLife-Framework/issues/474#issuecomment-2555207447_

**Comment by Bucket21-Gif** [comment]
https://pastebin.com/vMX0m3Lw RPT 
https://pastebin.com/7DwBK1Qw EXTDB3

**Comment by Scarso327** [comment]
` Config Error: db4856270: No such node (db4856270.IP)`

This line is the relevant one for us. 

```
[altislife]
IP = 127.0.0.1
Port = 3306
Username = arma
Password =
Database = altislife
```

This above section needs configuring so it can connect to your database in `extdb3-conf.ini`

**Comment by Bucket21-Gif** [comment]
i have already edited that its the extdb3 config yeah?

**Comment by Bucket21-Gif** [comment]
sorry just noticed you said it is the config

**Comment by Bucket21-Gif** [comment]
the db4856270 is my database name due to sql restrictions i cannot make another database called altislife but that was changed in the sql file aswell to allow db4856270

**Comment by Scarso327** [comment]
So the above example would be something like

```
[altislife]
IP = 127.0.0.1
Port = 3306
Username = arma
Password =
Database = db4856270
```

with the IP, Port, Usename and Password being whatever yours is. For obvious reasons don't post them here.

**Comment by Scarso327** [comment]
Are you able to show your config file with sensitive data removed?

**Comment by Bucket21-Gif** [comment]
https://pastebin.com/Eqj31r1K

**Comment by Scarso327** [comment]
Looks fine - make sure the creds are correct and no unexpected spaces exist

**Comment by Scarso327** [comment]
Have you changed the database name in description.ext

**Comment by Bucket21-Gif** [comment]
Yep

**Comment by Bucket21-Gif** [comment]
https://pastebin.com/0zq6LWFf

**Comment by Scarso327** [comment]
Yeah that needs changing back to altislife, it refers to the config in extdb not the actual name

**Comment by Bucket21-Gif** [comment]
Have changed it back to altislife now logs saying [21:54:33:366248 +00:00] [Thread 30684] extDB3: Config Error: altislife: No such node (altislife.IP)

**Comment by Scarso327** [comment]
I assume your extdb config remains in the same place? I am not having an issue configuring servers locally so there will be something with that config.

**Comment by Bucket21-Gif** [comment]
have been trying to work with hosting provider extdb logs now say 
[12:21:02:172440 +00:00] [Thread 28628] extDB3: SQL: Initialized: Add Quotes around TEXT Datatypes mode: 2
[12:21:02:172643 +00:00] [Thread 28628] extDB3: SQL: Initialized: NULL = ""

**Comment by Scarso327** [comment]
@Bucket21-Gif That is good - now you're getting that are you still getting black screen? If so what are your RPT logs showing?

**Comment by Bucket21-Gif** [comment]
https://pastebin.com/QWvpianX Yes still black screen

**Comment by Scarso327** [comment]
Looks fine, what about client rpt? You can access them via %localappdata% then arma 3

**Comment by Bucket21-Gif** [comment]
https://pastebin.com/0SU9RVww

**Comment by Bucket21-Gif** [comment]
Server RPT https://pastebin.com/y6MsqrfS
Client RPT https://pastebin.com/vQaWnqhJ

**Comment by Scarso327** [comment]
Is this client rpt definitely the latest? The server shows the "[DEBUG]" flag correctly but the client doesn't.

**Comment by Bucket21-Gif** [comment]
it was but have just rejoined the server pressed the respawn to bypass the black screen and walked around trying to do a few things to get it to show and this is what its come up with. https://pastebin.com/qr9zLbJk

**Comment by Scarso327** [comment]
Any extdb errors?

**Comment by Bucket21-Gif** [comment]
Still black screen and https://pastebin.com/yJgMsMCE

**Comment by Bucket21-Gif** [comment]
still black screen and https://pastebin.com/yJgMsMCE

**Comment by Scarso327** [comment]
@Bucket21-Gif Update your mission to latest from the master branch and it should all work now.

**Comment by Bucket21-Gif** [comment]
So i did still load into a black screen but pressed re spawn and everything is working now and updating the database

**Comment by Bucket21-Gif** [comment]
Thank you
