### ISSUE TITLE
Admin 

### ISSUE THREAD

**Issue by Bucket21-Gif** [Scarso327/AltisLife-Framework#481]
Hi 
How do you use the admin menu i seen your video saying should be shift f1 i have logged in as admin using #login but cannot login myself as onduty by pressing shift + f1

Thanks

**Comment by Scarso327** [comment]
You need to set your admin level in the database

**Comment by Bucket21-Gif** [comment]
i have set that to level 5

**Comment by Scarso327** [comment]
Will need to see RPT's and Extdb logs to see if any errors are happening.

**Comment by Bucket21-Gif** [comment]
only thing in extdb is 
extDB3: Found extdb3-conf.ini
extDB3: Detected 32 Cores, Setting up 6 Worker Threads
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...
extDB3: ...


[18:53:37:590683 +00:00] [Thread 22052] extDB3: SQL: Initialized: Add Quotes around TEXT Datatypes mode: 2
[18:53:37:590951 +00:00] [Thread 22052] extDB3: SQL: Initialized: NULL = ""
[18:53:37:591002 +00:00] [Thread 22052] extDB3: Locked
https://github.com/user-attachments/files/18214711/For.Scarso.RPT.log.txt

**Comment by Bucket21-Gif** [comment]
![Admin](https://github.com/user-attachments/assets/acfeb262-cc07-4c0a-a517-a04ce48a23a0)

**Comment by Bucket21-Gif** [comment]
if i put in debug call ULP_fnc_toggleAdminGear it does put me as on duty admin but obviously still no f1 option

**Comment by Scarso327** [comment]
Do you have a standard QWERTY keyboard?

**Comment by Bucket21-Gif** [comment]
Yes also just checking if part of same problem what his surrender key meant to be ? and are you suppose to be able to press windows key to open up car flip menu ?

**Comment by Bucket21-Gif** [comment]
i dont know if relevant but its small keyboard so 1 and f1 share same key hold fn to use the f1

**Comment by Bucket21-Gif** [comment]
nevermind as i say that i must not have been pressing the fn key

**Comment by Bucket21-Gif** [comment]
Sorry about wasting your time
