### ISSUE TITLE
Whitelisted

### ISSUE THREAD

**Issue by Bucket21-Gif** [Scarso327/AltisLife-Framework#498]
Hi how would i go about making some of the whitelisted slots public have been trying to look through files but cannot figure it out.
Thanks

**Comment by Scarso327** [comment]
Whitelisting is handled in [`Functions >> Initialisations >> fn_initialisation.sqf`](https://github.com/Scarso327/AltisLife-Framework/blob/master/Client%20Side/Framework/Functions/Initialisation/fn_initialisation.sqf#L40) line 40.

You'd need to add some logic here to ignore these checks if in a certain slot. This can be done using the variable name of the unit or a variable you set.

**Comment by Bucket21-Gif** [comment]
Perfect thank you
